### ISSUE TITLE
diocles curve number token

### ISSUE THREAD

**Issue by jacopogrecodalceo** [johannphilippe/hypercurve#9]
Hello,
I have some problem with the diocles curve.
Wherever I try to use it I get this error:

`error: syntax error, unexpected NUMBER_TOKEN  (token ".5")`

e.g.
```
giex	hc_gen 0, 8192, 0, \
			hc_segment(1/2, 1, hc_diocles(1)), \
			hc_segment(1/2, 0, hc_diocles(.5))
```

**Comment by johannphilippe** [comment]
`hc_diocles_curve` should be better, as all curve algorithms end with "curve" suffix

**Comment by johannphilippe** [comment]
Is it working like that ?

**Comment by jacopogrecodalceo** [comment]
yes ! I'm sorry, you're right. I missed the "_curve" appendix !
